# Generated by Django 6.0.2 on 2026-02-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('education', models.TextField(blank=True)),
                ('visa_status', models.CharField(blank=True, max_length=50)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
    ]
