# Generated by Django 6.0.2 on 2026-05-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_title_profile_country'),
        ('skills', '0002_track_skilltheme_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='selected_tracks',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='skills.track'),
        ),
    ]
