# Generated by Django 6.0.2 on 2026-05-25 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('track_type', models.CharField(choices=[('CORE', 'Core Essentials'), ('DOMAIN', 'Standard Professional Domain'), ('SPECIAL', 'Advanced Specialization')], default='DOMAIN', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='skilltheme',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='skills.track'),
        ),
    ]
