# Generated by Django 6.0.2 on 2026-05-25 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_track_skilltheme_track'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userskill',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userskill',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skills.skillsubcategory'),
        ),
        migrations.RemoveField(
            model_name='userskill',
            name='skill',
        ),
    ]
