# Generated by Django 6.0.2 on 2026-05-25 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_selected_tracks'),
        ('skills', '0003_alter_userskill_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userskill',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.skillsubcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='userskill',
            unique_together={('profile', 'sub_category')},
        ),
    ]
